### ISSUE TITLE
Linux builds fail to run with libmpv error

### ISSUE THREAD

**Issue by sashazurek** [kodjodevf/mangayomi#168] opened 2024-05-06 10:14 UTC
### Steps to reproduce

1. Download latest release (both AppImage and zip are affected)
2. Attempt to execute Mangayomi

### Expected behavior

Mangayomi should open.

### Actual behavior

Running the AppImage or the executable in the ZIP file from a command line fails with error `error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory`.

### Mangayomi version

0.2.25

### Device

PC, Fedora 39

### Other details

This issue persists even after installing the `libmpv` development package on Fedora.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by kodjodevf** [comment] 2024-05-06 10:52
Try : `sudo ln -s /usr/lib/x86_64-linux-gnu/libmpv.so.2 /usr/lib/x86_64-linux-gnu/libmpv.so.1`

**Comment by sashazurek** [comment] 2024-05-06 23:13
Creating that symlink does allow the app to load in both releases.

**Comment by kodjodevf** [comment] 2024-05-07 11:09
Since the issue is resolved, I'm closing it.

**Closed by kodjodevf** 2024-05-07 11:09 UTC
